# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metric_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'metric_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14metric_service.proto\"\xf0\x02\n\x11SaveMetricRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12$\n\x1cuso_de_cpu_porcentagem_core0\x18\x02 \x01(\x01\x12$\n\x1cuso_de_cpu_porcentagem_core1\x18\x03 \x01(\x01\x12(\n uso_de_memoria_porcentagem_total\x18\x04 \x01(\x01\x12(\n uso_de_memoria_porcentagem_cache\x18\x05 \x01(\x01\x12\"\n\x1auso_de_memoria_bytes_total\x18\x06 \x01(\x01\x12/\n\'uso_de_armazenamento_porcentagem_discoC\x18\x07 \x01(\x01\x12/\n\'uso_de_armazenamento_porcentagem_discoD\x18\x08 \x01(\x01\x12)\n!uso_de_armazenamento_bytes_discoC\x18\t \x01(\x01\"1\n\x12SaveMetricResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\"\x13\n\x11GetMetricsRequest\".\n\x12GetMetricsResponse\x12\x18\n\x07metrics\x18\x01 \x03(\x0b\x32\x07.Metric\"\x84\x03\n\x06Metric\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12$\n\x1cuso_de_cpu_porcentagem_core0\x18\x04 \x01(\x01\x12$\n\x1cuso_de_cpu_porcentagem_core1\x18\x05 \x01(\x01\x12(\n uso_de_memoria_porcentagem_total\x18\x06 \x01(\x01\x12(\n uso_de_memoria_porcentagem_cache\x18\x07 \x01(\x01\x12\"\n\x1auso_de_memoria_bytes_total\x18\x08 \x01(\x01\x12/\n\'uso_de_armazenamento_porcentagem_discoC\x18\t \x01(\x01\x12/\n\'uso_de_armazenamento_porcentagem_discoD\x18\n \x01(\x01\x12)\n!uso_de_armazenamento_bytes_discoC\x18\x0b \x01(\x01\x32}\n\rMetricService\x12\x35\n\nSaveMetric\x12\x12.SaveMetricRequest\x1a\x13.SaveMetricResponse\x12\x35\n\nGetMetrics\x12\x12.GetMetricsRequest\x1a\x13.GetMetricsResponseB\x16\xaa\x02\x13MetricStorageServerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metric_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023MetricStorageServer'
  _globals['_SAVEMETRICREQUEST']._serialized_start=25
  _globals['_SAVEMETRICREQUEST']._serialized_end=393
  _globals['_SAVEMETRICRESPONSE']._serialized_start=395
  _globals['_SAVEMETRICRESPONSE']._serialized_end=444
  _globals['_GETMETRICSREQUEST']._serialized_start=446
  _globals['_GETMETRICSREQUEST']._serialized_end=465
  _globals['_GETMETRICSRESPONSE']._serialized_start=467
  _globals['_GETMETRICSRESPONSE']._serialized_end=513
  _globals['_METRIC']._serialized_start=516
  _globals['_METRIC']._serialized_end=904
  _globals['_METRICSERVICE']._serialized_start=906
  _globals['_METRICSERVICE']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
